### PR TITLE
feat(command-output): clear button

### PR DESCRIPTION
**Pull request by peppedeka**
implementation of clear button via eventEmitter from dummy component to root component

### CODE REVIEW

**Comment by andrea82** [comment]
Hi @peppedeka 
thanks for your contribution. could you move the clear button inside the "REDIS RESPONSES" h3 tag and position it on extreme right ? Also if we could use an icon instead of the "clear" label would be great!
Thanks so much!

**Comment by peppedeka** [comment]
HI @andrea82 
fixed!

**Comment by andrea82** [comment]
Ok... almost perfect. Is better to keep layout style for clear button as well, so if you could add the following style for icon and remove background and border of button style will be perfect.
`.h7 {
      font-size: 1rem;
      color: #7a0c00;
      font-weight: bolder;
    }` 

thanks.

**Comment by peppedeka** [comment]
done!

**Pull request merged**
