### PR TITLE
improvement: introduce response observables flow

### PR DESCRIPTION
**Pull request by peppedeka**

### CODE REVIEW

**Comment by andrea82** [comment]
Hi @peppedeka 
what do you think about using merge operator for commands response and clear actions?
Something like this:
`this.responses$ = merge(this.redisConnectService.response$, this.currentResponseBs.asObservable()).pipe(
      scan((a, c) => c != null ? [...a, c] : [], []),
    );`

in this way we can remove the subscription inside the component .ts file, method destroy and lines from 23 to 25 as well.
Do you think is a good idea?

**Comment by peppedeka** [comment]
Good idea,
i remove useless **subscription** and implementation of **ngDestroy**.
i'm follow you hint, used static **merge** operators but i applied  **catchError** operator for handling external service call (because inject var can be undefined and generate error inside merge that can be break the flow)
I don't remove **currentResponse$** getter because is used by **async** pipe inside the app.component template

**Comment by andrea82** [comment]
Yes absolutely right, 
we still have to add an error handler so for now your fix is fine, but wouldn't it be better to handle the error in  **RedisConnectService** service?  
Sorry but i've not found **currentResponse$** in app.component template, if it is necessary keep it, otherwise remove.

Thanks so much!

**Comment by peppedeka** [comment]
Sounds good!
i moved observables catching error to **redis-connect.service** 
yes :) **currentResponse$** is useless i removed it

**Pull request merged**
